/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HallIdRouteImport } from './routes/hall.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedHallRouteImport } from './routes/_authenticated/hall'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWorkerRouteRouteImport } from './routes/_authenticated/worker/route'
import { Route as AuthenticatedCustomerRouteRouteImport } from './routes/_authenticated/customer/route'
import { Route as AuthenticatedWorkerIndexRouteImport } from './routes/_authenticated/worker/index'
import { Route as AuthenticatedCustomerIndexRouteImport } from './routes/_authenticated/customer/index'
import { Route as AuthenticatedWorkerSupportRouteImport } from './routes/_authenticated/worker/support'
import { Route as AuthenticatedWorkerSettingsRouteImport } from './routes/_authenticated/worker/settings'
import { Route as AuthenticatedWorkerProfileRouteImport } from './routes/_authenticated/worker/profile'
import { Route as AuthenticatedWorkerNotificationsRouteImport } from './routes/_authenticated/worker/notifications'
import { Route as AuthenticatedWorkerJobsRouteImport } from './routes/_authenticated/worker/jobs'
import { Route as AuthenticatedWorkerEarningsRouteImport } from './routes/_authenticated/worker/earnings'
import { Route as AuthenticatedWorkerDocumentsRouteImport } from './routes/_authenticated/worker/documents'
import { Route as AuthenticatedWorkerCalendarRouteImport } from './routes/_authenticated/worker/calendar'
import { Route as AuthenticatedWorkerAvailabilityRouteImport } from './routes/_authenticated/worker/availability'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HallIdRoute = HallIdRouteImport.update({
  id: '/hall/$id',
  path: '/hall/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHallRoute = AuthenticatedHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRouteRoute =
  AuthenticatedWorkerRouteRouteImport.update({
    id: '/worker',
    path: '/worker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerRouteRoute =
  AuthenticatedCustomerRouteRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerIndexRoute =
  AuthenticatedWorkerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedCustomerIndexRoute =
  AuthenticatedCustomerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedWorkerSupportRoute =
  AuthenticatedWorkerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerSettingsRoute =
  AuthenticatedWorkerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerProfileRoute =
  AuthenticatedWorkerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerNotificationsRoute =
  AuthenticatedWorkerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerJobsRoute = AuthenticatedWorkerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedWorkerRouteRoute,
} as any)
const AuthenticatedWorkerEarningsRoute =
  AuthenticatedWorkerEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerDocumentsRoute =
  AuthenticatedWorkerDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerCalendarRoute =
  AuthenticatedWorkerCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)
const AuthenticatedWorkerAvailabilityRoute =
  AuthenticatedWorkerAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedWorkerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/worker': typeof AuthenticatedWorkerRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/hall': typeof AuthenticatedHallRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hall/$id': typeof HallIdRoute
  '/worker/availability': typeof AuthenticatedWorkerAvailabilityRoute
  '/worker/calendar': typeof AuthenticatedWorkerCalendarRoute
  '/worker/documents': typeof AuthenticatedWorkerDocumentsRoute
  '/worker/earnings': typeof AuthenticatedWorkerEarningsRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/notifications': typeof AuthenticatedWorkerNotificationsRoute
  '/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/worker/settings': typeof AuthenticatedWorkerSettingsRoute
  '/worker/support': typeof AuthenticatedWorkerSupportRoute
  '/customer/': typeof AuthenticatedCustomerIndexRoute
  '/worker/': typeof AuthenticatedWorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/hall': typeof AuthenticatedHallRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hall/$id': typeof HallIdRoute
  '/worker/availability': typeof AuthenticatedWorkerAvailabilityRoute
  '/worker/calendar': typeof AuthenticatedWorkerCalendarRoute
  '/worker/documents': typeof AuthenticatedWorkerDocumentsRoute
  '/worker/earnings': typeof AuthenticatedWorkerEarningsRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/notifications': typeof AuthenticatedWorkerNotificationsRoute
  '/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/worker/settings': typeof AuthenticatedWorkerSettingsRoute
  '/worker/support': typeof AuthenticatedWorkerSupportRoute
  '/customer': typeof AuthenticatedCustomerIndexRoute
  '/worker': typeof AuthenticatedWorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/_authenticated/worker': typeof AuthenticatedWorkerRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/hall': typeof AuthenticatedHallRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/hall/$id': typeof HallIdRoute
  '/_authenticated/worker/availability': typeof AuthenticatedWorkerAvailabilityRoute
  '/_authenticated/worker/calendar': typeof AuthenticatedWorkerCalendarRoute
  '/_authenticated/worker/documents': typeof AuthenticatedWorkerDocumentsRoute
  '/_authenticated/worker/earnings': typeof AuthenticatedWorkerEarningsRoute
  '/_authenticated/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/_authenticated/worker/notifications': typeof AuthenticatedWorkerNotificationsRoute
  '/_authenticated/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/_authenticated/worker/settings': typeof AuthenticatedWorkerSettingsRoute
  '/_authenticated/worker/support': typeof AuthenticatedWorkerSupportRoute
  '/_authenticated/customer/': typeof AuthenticatedCustomerIndexRoute
  '/_authenticated/worker/': typeof AuthenticatedWorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/features'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/customer'
    | '/worker'
    | '/admin'
    | '/hall'
    | '/organization'
    | '/vendor'
    | '/auth/callback'
    | '/hall/$id'
    | '/worker/availability'
    | '/worker/calendar'
    | '/worker/documents'
    | '/worker/earnings'
    | '/worker/jobs'
    | '/worker/notifications'
    | '/worker/profile'
    | '/worker/settings'
    | '/worker/support'
    | '/customer/'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/features'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/admin'
    | '/hall'
    | '/organization'
    | '/vendor'
    | '/auth/callback'
    | '/hall/$id'
    | '/worker/availability'
    | '/worker/calendar'
    | '/worker/documents'
    | '/worker/earnings'
    | '/worker/jobs'
    | '/worker/notifications'
    | '/worker/profile'
    | '/worker/settings'
    | '/worker/support'
    | '/customer'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/features'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/research'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/_authenticated/customer'
    | '/_authenticated/worker'
    | '/_authenticated/admin'
    | '/_authenticated/hall'
    | '/_authenticated/organization'
    | '/_authenticated/vendor'
    | '/auth/callback'
    | '/hall/$id'
    | '/_authenticated/worker/availability'
    | '/_authenticated/worker/calendar'
    | '/_authenticated/worker/documents'
    | '/_authenticated/worker/earnings'
    | '/_authenticated/worker/jobs'
    | '/_authenticated/worker/notifications'
    | '/_authenticated/worker/profile'
    | '/_authenticated/worker/settings'
    | '/_authenticated/worker/support'
    | '/_authenticated/customer/'
    | '/_authenticated/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  HallIdRoute: typeof HallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall/$id': {
      id: '/hall/$id'
      path: '/hall/$id'
      fullPath: '/hall/$id'
      preLoaderRoute: typeof HallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hall': {
      id: '/_authenticated/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof AuthenticatedHallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/': {
      id: '/_authenticated/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof AuthenticatedWorkerIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/customer/': {
      id: '/_authenticated/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof AuthenticatedCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/worker/support': {
      id: '/_authenticated/worker/support'
      path: '/support'
      fullPath: '/worker/support'
      preLoaderRoute: typeof AuthenticatedWorkerSupportRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/settings': {
      id: '/_authenticated/worker/settings'
      path: '/settings'
      fullPath: '/worker/settings'
      preLoaderRoute: typeof AuthenticatedWorkerSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/profile': {
      id: '/_authenticated/worker/profile'
      path: '/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof AuthenticatedWorkerProfileRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/notifications': {
      id: '/_authenticated/worker/notifications'
      path: '/notifications'
      fullPath: '/worker/notifications'
      preLoaderRoute: typeof AuthenticatedWorkerNotificationsRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/jobs': {
      id: '/_authenticated/worker/jobs'
      path: '/jobs'
      fullPath: '/worker/jobs'
      preLoaderRoute: typeof AuthenticatedWorkerJobsRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/earnings': {
      id: '/_authenticated/worker/earnings'
      path: '/earnings'
      fullPath: '/worker/earnings'
      preLoaderRoute: typeof AuthenticatedWorkerEarningsRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/documents': {
      id: '/_authenticated/worker/documents'
      path: '/documents'
      fullPath: '/worker/documents'
      preLoaderRoute: typeof AuthenticatedWorkerDocumentsRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/calendar': {
      id: '/_authenticated/worker/calendar'
      path: '/calendar'
      fullPath: '/worker/calendar'
      preLoaderRoute: typeof AuthenticatedWorkerCalendarRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
    '/_authenticated/worker/availability': {
      id: '/_authenticated/worker/availability'
      path: '/availability'
      fullPath: '/worker/availability'
      preLoaderRoute: typeof AuthenticatedWorkerAvailabilityRouteImport
      parentRoute: typeof AuthenticatedWorkerRouteRoute
    }
  }
}

interface AuthenticatedCustomerRouteRouteChildren {
  AuthenticatedCustomerIndexRoute: typeof AuthenticatedCustomerIndexRoute
}

const AuthenticatedCustomerRouteRouteChildren: AuthenticatedCustomerRouteRouteChildren =
  {
    AuthenticatedCustomerIndexRoute: AuthenticatedCustomerIndexRoute,
  }

const AuthenticatedCustomerRouteRouteWithChildren =
  AuthenticatedCustomerRouteRoute._addFileChildren(
    AuthenticatedCustomerRouteRouteChildren,
  )

interface AuthenticatedWorkerRouteRouteChildren {
  AuthenticatedWorkerAvailabilityRoute: typeof AuthenticatedWorkerAvailabilityRoute
  AuthenticatedWorkerCalendarRoute: typeof AuthenticatedWorkerCalendarRoute
  AuthenticatedWorkerDocumentsRoute: typeof AuthenticatedWorkerDocumentsRoute
  AuthenticatedWorkerEarningsRoute: typeof AuthenticatedWorkerEarningsRoute
  AuthenticatedWorkerJobsRoute: typeof AuthenticatedWorkerJobsRoute
  AuthenticatedWorkerNotificationsRoute: typeof AuthenticatedWorkerNotificationsRoute
  AuthenticatedWorkerProfileRoute: typeof AuthenticatedWorkerProfileRoute
  AuthenticatedWorkerSettingsRoute: typeof AuthenticatedWorkerSettingsRoute
  AuthenticatedWorkerSupportRoute: typeof AuthenticatedWorkerSupportRoute
  AuthenticatedWorkerIndexRoute: typeof AuthenticatedWorkerIndexRoute
}

const AuthenticatedWorkerRouteRouteChildren: AuthenticatedWorkerRouteRouteChildren =
  {
    AuthenticatedWorkerAvailabilityRoute: AuthenticatedWorkerAvailabilityRoute,
    AuthenticatedWorkerCalendarRoute: AuthenticatedWorkerCalendarRoute,
    AuthenticatedWorkerDocumentsRoute: AuthenticatedWorkerDocumentsRoute,
    AuthenticatedWorkerEarningsRoute: AuthenticatedWorkerEarningsRoute,
    AuthenticatedWorkerJobsRoute: AuthenticatedWorkerJobsRoute,
    AuthenticatedWorkerNotificationsRoute:
      AuthenticatedWorkerNotificationsRoute,
    AuthenticatedWorkerProfileRoute: AuthenticatedWorkerProfileRoute,
    AuthenticatedWorkerSettingsRoute: AuthenticatedWorkerSettingsRoute,
    AuthenticatedWorkerSupportRoute: AuthenticatedWorkerSupportRoute,
    AuthenticatedWorkerIndexRoute: AuthenticatedWorkerIndexRoute,
  }

const AuthenticatedWorkerRouteRouteWithChildren =
  AuthenticatedWorkerRouteRoute._addFileChildren(
    AuthenticatedWorkerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomerRouteRoute: typeof AuthenticatedCustomerRouteRouteWithChildren
  AuthenticatedWorkerRouteRoute: typeof AuthenticatedWorkerRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHallRoute: typeof AuthenticatedHallRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomerRouteRoute: AuthenticatedCustomerRouteRouteWithChildren,
  AuthenticatedWorkerRouteRoute: AuthenticatedWorkerRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHallRoute: AuthenticatedHallRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  HallIdRoute: HallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
